"""Initial migration

Revision ID: 87c5288a5985
Revises:
Create Date: 2025-10-24 14:05:14.905511

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87c5288a5985"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("prod_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock_level", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("prod_id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("wallet_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "cart_item",
        sa.Column("cart_item_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prod_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["product.prod_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("cart_item_id"),
    )
    op.create_table(
        "order",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "order_item",
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("prod_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=True),
        sa.Column(
            "price_at_purchase", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["product.prod_id"],
        ),
        sa.PrimaryKeyConstraint("order_item_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_item")
    op.drop_table("order")
    op.drop_table("cart_item")
    op.drop_table("user")
    op.drop_table("product")
    # ### end Alembic commands ###
