"""empty message

Revision ID: 986b49b6121a
Revises: c242a2cc59c1
Create Date: 2025-10-29 17:14:39.241556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986b49b6121a'
down_revision = 'c242a2cc59c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('grand_total')
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('grand_total', sa.NUMERIC(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('grand_total')

    # ### end Alembic commands ###
