"""empty message

Revision ID: aabf772748d2
Revises: 986b49b6121a
Create Date: 2025-10-29 20:58:07.402832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabf772748d2'
down_revision = '986b49b6121a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('sub_total')

    # ### end Alembic commands ###
